base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('bookings/', views.bookings, name="bookings"),
    path('logout/', views.logoutView, name='logoutView')
]

cleaning_company/urls.py
from django.contrib import admin
from django.urls import path, include

from cleaning_company.core import views as core_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", core_views.index, name="home"),
    path("client_dashbord/", include('base.urls')),
    path("register_page/", core_views.registerView, name='register_page'),
    path("", include('django.contrib.auth.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Team(models.Model):
    name = models.CharField(max_length=100)

    # Add other fields for the team's details (e.g., description, location, contact info)

    def __str__(self):
        return self.name


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    # Add other fields related to the appointment (e.g., service type, additional notes)

    def __str__(self):
        return f"{self.user}'s Appointment with {self.team.name} on {self.date} at {self.start_time}"

base/forms.py
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Appointment


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['team', 'date', 'start_time', 'end_time']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

    def clean(self):
        cleaned_data = super().clean()
        team = cleaned_data.get('team')
        date = cleaned_data.get('date')
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        # Check if there are any existing appointments for the selected team and date
        existing_appointments = Appointment.objects.filter(
            team=team,
            date=date,
        )

        for appointment in existing_appointments:
            if (appointment.start_time <= start_time <= appointment.end_time) or \
                    (appointment.start_time <= end_time <= appointment.end_time):
                raise ValidationError(
                    _('The team is already booked for this date and time. Please choose another date/time.')
                )

        return cleaned_data

cleaning_company/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(required=True)
    email = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Appointment
from .forms import AppointmentForm


# Create your views here.
@login_required
def dashboard(request):
    client_appointments = Appointment.objects.all().filter(user=request.user)
    return render(request, 'base/dashboard.html', {'appointments': client_appointments})


@login_required
def bookings(request):
    if request.POST:
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.user = request.user
            appointment.save()
            messages.success(request, 'Appointment booked successfully!')
            return redirect('base:bookings')  # Redirect to a success page after booking
        else:
            for errors in form.errors.values():
                for error in errors:
                    messages.error(request, f"{error}")
    form = AppointmentForm()
    return render(request, 'base/bookings.html', {'form': form})


def logoutView(request):
    logout(request)
    return redirect('home')

cleaning_company/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import UserRegisterForm

def index(request):
    return render(request, 'core/index.html')

def registerView(request):
    if request.POST:
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("base:dashboard")

    form = UserRegisterForm()
    return render(request, 'registration/register.html', {"form":form})

base/templates/base/bookings.html
{% extends 'base/dashboard_structure.html' %}
{% block title %}Booking Page{% endblock title %}

{% block cont %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center mb-4">Book an Appointment</h1>
                {% if messages %}
                    <ul class="alert alert-danger">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

            <div class="masthead">
            <div class="masthead-content text-white">
                <div class="container-fluid px-4 px-lg-0">


                     <form method="post" class="contactForm">
                    {% csrf_token %}
                    <div>
                        <label for="{{ form.team.id_for_label }}">Team</label>
                        {{ form.team }}
                    </div>
                    <div>
                        <label for="{{ form.date.id_for_label }}">Date</label>
                        {{ form.date }}
                    </div>
                    <div >
                        <label for="{{ form.start_time.id_for_label }}">Start Time</label>
                        {{ form.start_time }}
                    </div>
                    <div >
                        <label for="{{ form.end_time.id_for_label }}">End Time</label>
                        {{ form.end_time }}
                    </div>
                    <button type="submit">Submit</button>
                </form>
                </div>
            </div>
        </div>

            </div>
        </div>
    </div>


{% endblock cont %}

base/templates/base/dashboard.html
{% extends 'base/dashboard_structure.html' %}
{% block title %}dashboard{% endblock title %}


{% block cont %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">


    {% if user.is_authenticated %}
        <h1>{{ user.get_username }} Appointments</h1>
    {% endif %}
<tabel class="table table-hover table-dark">
    <thead>
    <tr>
        <th scope="col">Team</th>
        <th scope="col">Date</th>
        <th scope="col">start time</th>
        <th scope="col">end time</th>
    </tr>
    </thead>
    <br>
    <tbody>
    {% for appointment in appointments %}
        <tr>
            <th>{{ appointment.team.name }}</th>
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.start_time }}</td>
            <td>{{ appointment.end_time }}</td>
        </tr>
        <br>
    {% endfor %}
    </tbody>
</tabel>

            </div>
        </div>
    </div>


{% endblock cont %}

base/templates/base/dashboard_structure.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Cleaning Service</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'core/assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'core/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/aos.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'core/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


</head>

<body class="index-page"  data-bs-spy="scroll" data-bs-target="#navmenu">

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container-fluid d-flex align-items-center justify-content-between">

        <a href="#header" class="logo d-flex align-items-center me-auto me-xl-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <h1>Cleaning Company</h1>
            <span>.</span>
        </a>

        <!-- Nav Menu -->
        <nav id="navmenu" class="navmenu">
            <ul>
                <li><a href="{% url 'base:dashboard' %}" class="active">Dashboard</a></li>
                <li><a href="{% url 'base:bookings' %}" class="active">Make Booking</a></li>
                <li><a href="{% url 'base:logoutView' %}" class="active">logout</a></li>

            </ul>

            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav><!-- End Nav Menu -->


    </div>
</header><!-- End Header -->

<main id="main">

    <!-- Hero Section - Home Page -->
    <section  class="hero">

        <img src="{% static 'core/assets/img/hero-bg.jpg' %}" alt="" data-aos="fade-in">

        <div class="container">
            <div class="row">
                <div id="booking">
                {% block cont %}
                {% endblock cont %}
                </div>
            </div>
        </div>

    </section><!-- End Hero Section -->


</main>

<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Preloader -->
<div id="preloader">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
</div>

<!-- Vendor JS Files -->
<script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'core/js/glightbox.min.js' %}"></script>
<script src="{% static 'core/js/purecounter_vanilla.js' %}"></script>
<script src="{% static 'core/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'core/js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'core/js/aos.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'core/js/main.js' %}"></script>

</body>

</html>